name: Build/release Passwordstore GUI app

on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Build for Linux
        if: matrix.os == 'ubuntu-latest'
        run: npm run build:linux -- --publish=never

      - name: Build for Mac
        if: matrix.os == 'macos-latest'
        run: npm run build:mac -- --publish=never

#      - name: Build for Windows
#        if: matrix.os == 'windows-latest'
#        run: npm run build:win -- --publish=never

      - name: Debug - List Output Files
        run: ls -alR dist/

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          files: |
            dist/**/*.exe
            dist/**/*.zip
            dist/**/*.dmg
            dist/**/*.AppImage
            dist/**/*.snap
            dist/**/*.deb
            dist/**/*.rpm
            dist/**/*.tar.gz
            dist/**/*.yml
            dist/**/*.blockmap
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
